version: 2
jobs:
  test-ouroboros:
    docker:
      - image: ameier38/docker-ci
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Run Tests
          command: |
            cd ./src/Tests
            docker-compose build test
            docker-compose up -d eventstore
            sleep 10s
            docker-compose run --rm test
  build-ouroboros:
    docker:
      - image: microsoft/dotnet:2.1
    steps:
      - checkout
      - run:
          name: Build nuget package
          command: |
            cd ./src/Ouroboros
            dotnet pack -c Release
      - run:
          name: Push nuget package
          command: |
            cd ./src/Ouroboros/bin/Release
            dotnet nuget push Ouroboros.1.0.0.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json

workflows:
   version: 2
   test:
     jobs:
       - test-ouroboros
       - build-ouroboros:
           filters:
             branches:
               only: develop
           requires:
             - test-ouroboros
